Repository pratyushmp/Batua, pull requests merged in 2021-03, with the labels that each got.

#12 Created Login screen
  lib/login_screen.dart
  lib/main.dart
Labels: GSSOC21, Level2

#14 Added Google SignIn (#3)
  android/app/google-services.json
  lib/google_signin.dart
  lib/home_screen.dart
  lib/login_screen.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level2

#19 Added Contributor
  README.md
Labels: GSSOC21, Level0

#23 Issue 10
  android/app/google-services.json
  lib/auth_wrapper.dart
  lib/authentication_service.dart
  lib/home_screen.dart
  lib/loading.dart
  lib/login_screen.dart
  lib/main.dart
  lib/sign_up.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level2

#24 Created screen to collect user details
  lib/user_details_screen.dart
  lib/utils/constants.dart
Labels: GSSOC21, Level2

#32 Home screen added
  lib/home_screen.dart
  lib/sign_up.dart
  lib/user_details_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level2

#35 Optimized images using imgbot
  Batua1.png
  Batua2.png
Labels: GSSOC21, Level1

#37 Resolved SignUp and logIn button Problem
  lib/authentication_service.dart
  lib/home_screen.dart
  lib/login_screen.dart
  lib/main.dart
  lib/sign_up.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level2

#62 Fixes Issue #56
  lib/home_screen.dart
  lib/login_screen.dart
  lib/main.dart
  lib/sign_up.dart
  lib/user_details_screen.dart
  lib/utils/constants.dart
  lib/utils/route_page.dart
Labels: GSSOC21, Level2
